import type { Metadata } from 'next'
import { SpeedInsights } from '@vercel/speed-insights/next'
import './globals.css'

import { Inter } from 'next/font/google'

import { AntdRegistry } from '@ant-design/nextjs-registry'
import { Header } from '@components/app'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' data-theme='light'>
			<AntdRegistry>
				<body className={inter.className + ' flex flex-col h-screen '}>
					<Header />
					<main className='overflow-auto'>
						{children}
						<SpeedInsights />
					</main>
				</body>
			</AntdRegistry>
		</html>
	)
}
